# Используем более новую версию Node
FROM node:18-alpine

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем файлы package.json и package-lock.json (если есть)
COPY package.json package-lock.json* ./

# Устанавливаем зависимости
RUN npm install

# Копируем остальные файлы проекта
COPY . .

EXPOSE 5173

# Запуск приложения
CMD ["npm", "run", "dev"]