# Используем официальный Node образ (на основе Alpine для легкости)
FROM node:16-alpine

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем package.json (и package-lock.json, если есть) для установки зависимостей
COPY package.json package-lock.json* ./

# Устанавливаем зависимости
RUN npm install

# Копируем остальные файлы проекта
COPY . .

# Открываем порт приложения (по умолчанию React запускается на 3000)
EXPOSE 3000

# Запуск React-приложения
CMD ["npm", "run", "dev"]