# Используем более новую версию Node
FROM node:18-alpine

# Устанавливаем рабочую директорию
WORKDIR /monamour/frontend

# Копируем файлы package.json и package-lock.json (если есть)
COPY package.json package-lock.json* ./

# Устанавливаем зависимости
RUN npm install

# Копируем остальные файлы проекта
COPY . .

# Открываем порт (по умолчанию Vite использует 3000)
EXPOSE 3000

# Запуск приложения
CMD ["npm", "run", "dev"]