version: '3.9'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: bash -c "./wait_for_postgres.sh && python monamour/manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/monamour/backend
    ports:
      - "8000:8000"
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules 
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
    # Используем polling для надёжного отслеживания файлов в контейнере
    - CHOKIDAR_USEPOLLING=true

volumes:
  postgres_data: