# backend/Dockerfile

FROM python:3.11-slim

# Устанавливаем рабочую директорию в папку backend
WORKDIR /monamour/backend

# Устанавливаем зависимости системы
RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    postgresql-client && \
    apt-get clean

# Копируем скрипт ожидания
COPY wait_for_postgres.sh /monamour/backend/wait_for_postgres.sh

# Делаем скрипт исполнимым
RUN chmod +x /monamour/backend/wait_for_postgres.sh

# Копируем файл зависимостей
COPY requirements.txt .

# Устанавливаем зависимости проекта
RUN pip install --no-cache-dir -r requirements.txt

# Копируем все файлы проекта (будет скопирована папка monamour с manage.py)
COPY . .

# Экспортируем порт приложения
EXPOSE 8000

# Запуск сервера Django.
# Обратите внимание, что manage.py лежит в поддиректории monamour
CMD ["python", "monamour/manage.py", "runserver", "0.0.0.0:8000"]