# Generated by Django 5.0.4 on 2025-05-18 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_cart_options_alter_order_options_and_more'),
        ('store', '0004_alter_artist_biography_alter_artist_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paintings',
            field=models.ManyToManyField(related_name='orders', through='orders.OrderItem', to='store.painting', verbose_name='Картины в заказе'),
        ),
    ]
