# Generated by Django 5.0.4 on 2025-05-18 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_paintings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['-added_at', 'user'], 'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзина'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-order_date', 'user'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказ'},
        ),
    ]
