# Generated by Django 5.0.4 on 2025-06-01 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_cart_options_alter_order_options'),
        ('store', '0007_artist_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='painting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.painting'),
        ),
    ]
