# Generated by Django 5.0.4 on 2025-04-04 20:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'Рекламный баннер', 'verbose_name_plural': 'Рекламные баннеры'},
        ),
        migrations.AlterModelOptions(
            name='painting',
            options={'verbose_name': 'Картина', 'verbose_name_plural': 'Картины'},
        ),
        migrations.RemoveField(
            model_name='banner',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='painting',
            name='city_created',
        ),
        migrations.RemoveField(
            model_name='painting',
            name='image_url',
        ),
        migrations.AddField(
            model_name='artist',
            name='image',
            field=models.ImageField(blank=True, upload_to='Artists/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='artist',
            name='name',
            field=models.CharField(default='smth', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='banner_image',
            field=models.ImageField(default='smth', upload_to='Banners/', verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gallery',
            name='gallery_photo_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='headline',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='link',
            field=models.URLField(blank=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='subheadline',
            field=models.CharField(blank=True, max_length=255, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.artist', verbose_name='Художник'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='dimensions',
            field=models.CharField(blank=True, max_length=100, verbose_name='Размеры'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.gallery', verbose_name='Галерея'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='status',
            field=models.CharField(choices=[('available', 'В наличии'), ('sold', 'Продано')], default='available', max_length=10, verbose_name='Наличие'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='technique',
            field=models.CharField(blank=True, max_length=255, verbose_name='Техника'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.CreateModel(
            name='PaintingImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='paintings/', verbose_name='Изображение')),
                ('painting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.painting', verbose_name='Картина')),
            ],
            options={
                'verbose_name': 'Изображение картины',
                'verbose_name_plural': 'Изображения картин',
            },
        ),
    ]
