# Generated by Django 5.0.4 on 2025-04-20 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_banner_options_alter_painting_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Галлерея', 'verbose_name_plural': 'Галлереи'},
        ),
        migrations.RemoveField(
            model_name='artist',
            name='portfolio',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='social_links',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='gallery_photo_url',
        ),
        migrations.AddField(
            model_name='gallery',
            name='gallery_image',
            field=models.ImageField(blank=True, upload_to='gallery/', verbose_name='Изображение'),
        ),
    ]
