# Generated by Django 5.0.4 on 2025-05-18 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_artist_biography_alter_artist_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ['name'], 'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['created_at', 'name'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['name'], 'verbose_name': 'Галлерея', 'verbose_name_plural': 'Галлереи'},
        ),
        migrations.AlterModelOptions(
            name='painting',
            options={'ordering': ['added_at', 'title'], 'verbose_name': 'Картина', 'verbose_name_plural': 'Картины'},
        ),
    ]
