# Generated by Django 5.0.4 on 2025-06-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_artist_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='artist_resumes/', verbose_name='Резюме (PDF)'),
        ),
    ]
