# Generated by Django 5.0.4 on 2025-06-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_artist_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='website',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Официальный сайт'),
        ),
    ]
