# Generated by Django 5.0.4 on 2025-06-13 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_artist_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paintingimage',
            name='painting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.painting', verbose_name='Картина'),
        ),
    ]
