# Generated by Django 5.0.4 on 2025-06-14 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_artistreview'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='artistreview',
            unique_together=set(),
        ),
    ]
